site_name: "DeepWiki — Registro"
site_description: "Documentación del proyecto Registro (DeepWiki dump)"
docs_dir: "docs/mkdocs"
use_directory_urls: false

theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default        # claro
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate          # oscuro
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Modo claro


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.highlight

nav:
  - "Overview": "Overview.md"
  - "Getting Started": "Getting-Started.md"

  - "Architecture Overview":
      - "Architecture Overview": "Architecture-Overview.md"
      - "System Components": "System-Components.md"
      - "Technology Stack": "Technology-Stack.md"
      - "Request Processing Pipeline": "Request-Processing-Pipeline.md"

  - "Application Bootstrap": "Application-Bootstrap.md"

  - "Routing System":
      - "Routing System": "Routing-System.md"
      - "Public Routes": "Public-Routes.md"
      - "Protected Routes": "Protected-Routes.md"
      - "API Endpoints": "API-Endpoints.md"

  - "Authentication & Authorization":
      - "Authentication & Authorization": "Authentication-&-Authorization.md"
      - "User Registration & Login": "User-Registration-&-Login.md"
      - "JWT Token Management": "JWT-Token-Management.md"
      - "verifyToken Middleware": "verifyToken-Middleware.md"

  - "Security Measures": "Security-Measures.md"

  - "Real-time Communication System":
      - "Real-time Communication System": "Real-time-Communication-System.md"
      - "Socket.IO Server Setup": "Socket.IO-Server-Setup.md"
      - "WebSocket Authentication": "WebSocket-Authentication.md"
      - "Room Management": "Room-Management.md"
      - "Message Handling": "Message-Handling.md"

  - "Product Management": "Product-Management.md"

  - "Support Chat System":
      - "Support Chat System": "Support-Chat-System.md"
      - "User Chat Interface": "User-Chat-Interface.md"
      - "Admin Chat Interface": "Admin-Chat-Interface.md"

  - "PDF Generation":
      - "PDF Generation": "PDF-Generation.md"
      - "Puppeteer PDF Generation": "Puppeteer-PDF-Generation.md"
      - "PDFKit PDF Generation": "PDFKit-PDF-Generation.md"

  - "Internationalization (i18n)": "Internationalization-(i18n).md"

  - "View Layer & Templates":
      - "Template Structure": "Template-Structure.md"
      - "Partial Components": "Partial-Components.md"
      - "Page Views": "Page-Views.md"

  - "Static Assets & Styling": "Static-Assets-&-Styling.md"

  - "Database Schema":
      - "Database Schema": "Database-Schema.md"
      - "usuarios Table": "usuarios-Table.md"
      - "productos Table": "productos-Table.md"
      - "mensajes Table": "mensajes-Table.md"

  - "API Reference":
      - "API Reference": "API-Reference.md"
      - "HTTP Endpoints": "HTTP-Endpoints.md"
      - "WebSocket Events": "WebSocket-Events.md"

  - "Deployment & Configuration": "Deployment-&-Configuration.md"

  # Opcional: dejar README al final o usarlo como portada si lo renombras a index.md
  - "README": "README.md"

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

